CC = cl
TARGET = rmtrash.exe
SRC = src\rmtrash.c

CFLAGS = /nologo /std:c11 /O2 /W4 /DWIN32_LEAN_AND_MEAN /GS-
CPPFLAGS =
LDFLAGS = /nologo /NODEFAULTLIB /ENTRY:mainCRTStartup /SUBSYSTEM:CONSOLE
LDLIBS = shell32.lib kernel32.lib

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CPPFLAGS) $(CFLAGS) /Fe:$@ $(SRC) /link $(LDFLAGS) $(LDLIBS)

clean:
	-del /Q $(TARGET) rmtrash.obj 2>NUL
